_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 55
            "4": 3.10.13
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
ODE_weight:
    value: 0.001
epochs:
    value: 50000
learning_rate:
    value: 0.03
number of output models:
    value: 1
resWidth:
    value: 40
