_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
ODE_weight:
    value: 0.01
epochs:
    value: 10000
learning_rate:
    value: 0.01
resWidth:
    value: 40
