_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
ODE_weight:
    value: 1
epochs:
    value: 2500
learning_rate:
    value: 0.005
num_models:
    value: 1
resDepth:
    value: 5
resWidth:
    value: 100
