_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
ODE_weight:
    value: 1
epochs:
    value: 11000
learning_rate:
    value: 1e-05
num_models:
    value: 1
resWidth:
    value: 64
